### ISSUE TITLE
문제3

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/javascript-onboarding#3]
## 🚀 기능 요구 사항

배달이가 좋아하는 369게임을 하고자 한다. 놀이법은 1부터 숫자를 하나씩 대면서, 3, 6, 9가 들어가는 숫자는 숫자를 말하는 대신 3, 6, 9의 개수만큼 손뼉을 쳐야 한다.

숫자 number가 매개변수로 주어질 때, 1부터 number까지 손뼉을 몇 번 쳐야 하는지 횟수를 return 하도록 solution 메서드를 완성하라.

### 제한사항

- number는 1 이상 10,000 이하인 자연수이다.

### 실행 결과 예시

| number | result |
| --- | --- |
| 13 | 4 |
| 33 | 14 |

### 어떻게 해결 할 것인가
- Max Case가 number가 10,000일때 이니깐 반복문으로 해결해도 될 것 같다.
- 1부터 number까지 모든 수를 탐색한다.
- 3, 6, 9가 포함된 만큼 count를 한다.
- 최종 count값을 리턴한다.

### TODO List
- [x] 3, 6, 9 counting을 해주는 함수 생성
- [x] 1 부터 number까지 반복 후 최종 count값 반환
- [x] refactoring 및 최종 pr 생성
