### ISSUE TITLE
문제4

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/javascript-onboarding#4]
## 🚀 기능 요구 사항

어느 연못에 엄마 말씀을 좀처럼 듣지 않는 청개구리가 살고 있었다. 청개구리는 엄마가 하는 말은 무엇이든 반대로 말하였다.

엄마 말씀 word가 매개변수로 주어질 때, 아래 청개구리 사전을 참고해 반대로 변환하여 return 하도록 solution 메서드를 완성하라.

| A | B | C | D | E | F | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V | W | X | Y | Z |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| Z | Y | X | W | V | U | T | S | R | Q | P | O | N | M | L | K | J | I | H | G | F | E | D | C | B | A |

### 제한사항

- word는 길이가 1 이상 1,000 이하인 문자열이다.
- 알파벳 외의 문자는 변환하지 않는다.
- 알파벳 대문자는 알파벳 대문자로, 알파벳 소문자는 알파벳 소문자로 변환한다.

### 실행 결과 예시

| word | result |
| --- | --- |
| "I love you" | "R olev blf" |

### 어떻게 해결 할 것인가
- 문자를 반대로 바꾸는 함수를 생성해야한다.
- 알파벳 외의 문자는 변환하지 않는다. (알파벳 판별 함수가 필요할 듯)
- 유니코드 함수를 사용해서 반대로 바꾸면 될 것 같다.
- A(65), Z(90), a(97), z(122)
- word를 배열화해서 idx를 순환하면서 반대로 바꾸는 함수에 넣어준다.
- 최종 결과를 다시 join()을 통해 반환한다.

### TODO List
- [x] 문자를 반대로 바꾸는 함수를 생성
- [x] word를 순환하며 최종 결과 리턴
- [x] refactoring 및 최종 pr 생성
