### ISSUE TITLE
문제5

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/javascript-onboarding#5]
## 🚀 기능 요구 사항

계좌에 들어있는 돈 일부를 은행에서 출금하고자 한다. 돈 담을 지갑이 최대한 가볍도록 큰 금액의 화폐 위주로 받는다.

돈의 액수 money가 매개변수로 주어질 때, 오만 원권, 만 원권, 오천 원권, 천 원권, 오백원 동전, 백원 동전, 오십원 동전, 십원 동전, 일원 동전 각 몇 개로 변환되는지 금액이 큰 순서대로 배열에 담아 return 하도록 solution 메서드를 완성하라.

### 제한사항

- money는 1 이상 1,000,000 이하인 자연수이다.

### 실행 결과 예시

| money | result |
| --- | --- |
| 50237	| [1, 0, 0, 0, 0, 2, 0, 3, 7] |
| 15000	| [0, 1, 1, 0, 0, 0, 0, 0, 0] |

### 어떻게 해결 할 것인가
- 해당문제는 그리디문제의 대표적인 유형이다.
- 가장 높은 금액부터 최대한 지갑에 담는 방식으로 각 단계에서 최적의 경우를 구해야한다.
- 화폐 마다 최대로 변환할 수 있는 count 함수를 생성한다.
- const 화폐 = [50000, 10000, 5000, 1000, 500, 100, 10, 1] 을 선언하고 반복문을 통해 대응하는 result 배열을 생성한다.

### TODO List
- [x] 최대로 변환할 수 있는 count 함수 생성 (매개변수는 화폐 금액)
- [x] const 화폐 배열을 순환하면서 같은 길이의 result 배열 생성 및 반환
- [x] refactoring 및 최종 pr 생성
