### ISSUE TITLE
문제6

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/javascript-onboarding#6]
## 🚀 기능 요구 사항

우아한테크코스에서는 교육생(이하 크루) 간 소통 시 닉네임을 사용한다. 간혹 비슷한 닉네임을 정하는 경우가 있는데, 이러할 경우 소통할 때 혼란을 불러일으킬 수 있다.

혼란을 막기 위해 크루들의 닉네임 중 **같은 글자가 연속적으로 포함** 될 경우 해당 닉네임 사용을 제한하려 한다. 이를 위해 같은 글자가 연속적으로 포함되는 닉네임을 신청한 크루들에게 알려주는 시스템을 만들려고 한다.

신청받은 닉네임 중 **같은 글자가 연속적으로 포함** 되는 닉네임을 작성한 지원자의 이메일 목록을 return 하도록 solution 메서드를 완성하라.

### 제한사항

- 두 글자 이상의 문자가 연속적으로 순서에 맞추어 포함되어 있는 경우 중복으로 간주한다.
- 크루는 1명 이상 10,000명 이하이다.
- 이메일은 이메일 형식에 부합하며, 전체 길이는 11자 이상 20자 미만이다.
- 신청할 수 있는 이메일은 `email.com` 도메인으로만 제한한다.
- 닉네임은 한글만 가능하고 전체 길이는 1자 이상 20자 미만이다.
- result는 이메일에 해당하는 부분의 문자열을 오름차순으로 정렬하고 중복은 제거한다.

### 실행 결과 예시

| forms | result |
| --- | --- |
| [ ["jm@email.com", "제이엠"], ["jason@email.com", "제이슨"], ["woniee@email.com", "워니"], ["mj@email.com", "엠제이"], ["nowm@email.com", "이제엠"] ] | ["jason@email.com", "jm@email.com", "mj@email.com"] |

### 어떻게 해결 할 것인가
- 최대 10,000명의 닉네임에서 2글자의 경우의 수를 모두 저장한다.(2글자를 key값으로 가지는 Map()자료형)
- key 중 value가 2이상인 key를 닉네임에 포함하는 사람은 중복된 사람이다.
- 최종 이메일 결과를 sort(오름차순 정렬)해서 반환한다.

### TODO List
- [x] 닉네임 전체 길이를 2글자씩 잘라 전체 순환을 해서 Map()에 저장하는 함수 생성
- [x] forms에서 중복된 사람을 추출하는 로직 or 함수 생성
- [x] 최종 결과를 sort 후 리턴
- [x] refactoring 및 최종 pr 생성
