### ISSUE TITLE
문제7

### ISSUE THREAD

**Issue by thinkanddoit** [thinkanddoit/javascript-onboarding#7]
## 🚀 기능 요구 사항

레벨 2의 팀 프로젝트 미션으로 SNS(Social Networking Service)를 만들고자 하는 팀이 있다. 팀에 속한 크루 중 평소 알고리즘에 관심이 많은 미스터코는 친구 추천 알고리즘을 구현하고자 아래와 같은 규칙을 세웠다.
- 사용자와 함께 아는 친구의 수 = 10점 
- 사용자의 타임 라인에 방문한 횟수 = 1점

사용자 아이디 user와 친구 관계를 담은 이차원 배열 friends, 사용자 타임 라인 방문 기록 visitors가 매개변수로 주어질 때, 미스터코의 친구 추천 규칙에 따라 점수가 가장 높은 순으로 정렬하여 최대 5명을 return 하도록 solution 메서드를 완성하라. 이때 추천 점수가 0점인 경우 추천하지 않으며, 추천 점수가 같은 경우는 이름순으로 정렬한다.

### 제한사항

- user는 길이가 1 이상 30 이하인 문자열이다.
- friends는 길이가 1 이상 10,000 이하인 배열이다.
- friends의 각 원소는 길이가 2인 배열로 [아이디 A, 아이디 B] 순으로 들어있다.
  - A와 B는 친구라는 의미이다.
  - 아이디는 길이가 1 이상 30 이하인 문자열이다.
- visitors는 길이가 0 이상 10,000 이하인 배열이다.
- 사용자 아이디는 알파벳 소문자로만 이루어져 있다.
- 동일한 친구 관계가 중복해서 주어지지 않는다.
- 추천할 친구가 없는 경우는 주어지지 않는다.

### 실행 결과 예시

| user   | friends                                                                                                                         | visitors                                      | result                    |
| ------ | ------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------- | ------------------------- |
| "mrko" | [ ["donut", "andole"], ["donut", "jun"], ["donut", "mrko"], ["shakevan", "andole"], ["shakevan", "jun"], ["shakevan", "mrko"] ] | ["bedi", "bedi", "donut", "bedi", "shakevan"] | ["andole", "jun", "bedi"] |

### 어떻게 해결 할 것인가
- 존재하는 모든 사람에 대한 정보를 배열형태로 저장해야한다.
- 각 사람에 대한 점수를 계산하는 함수를 생성한다.
- 점수를 바탕으로 sort한다. (점수가 0인 사람은 제외, 추천점수가 같다면 이름순)
- 해당 결과를 최종 반환한다.

### TODO List
- [x] friends를 전체 순환하면서 모든 사람에 대한 친구관계 정보를 저장 (Map 형태로 중복없이)
- [x] Map을 Array형태로 변환하면서 user의 친구정보와 비교해 아는친구에 대한 점수를 계산 및 저장
- [x] 타임라인 방문기록 정보도 반영
- [x] 점수를 바탕으로 sort 및 점수 0점 제외, 이미 친구인 사람 제외, 추천점수가 같다면 이름순 정렬
- [x] 최종 결과 배열을 리턴
- [x] refactoring 및 최종 pr 생성

**Comment by thinkanddoit** [comment]
error 발견 https://github.com/thinkanddoit/javascript-onboarding/commit/71dc6b55ce2ab0cfe1aaa5423473a9aa808df6d6#commitcomment-88263820

[수정](https://github.com/thinkanddoit/javascript-onboarding/commit/3acaa3924db556474701ad256d39c5cf3f6b56b8)
